name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
         node-version: 22
         cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          LOGTO_ENDPOINT: ${{ secrets.LOGTO_ENDPOINT }}
          LOGTO_APP_ID: ${{ secrets.LOGTO_APP_ID }}
          LOGTO_APP_SECRET: ${{ secrets.LOGTO_APP_SECRET }}
          LOGTO_COOKIE_ENCRYPTION_KEY: ${{ secrets.LOGTO_COOKIE_ENCRYPTION_KEY }}
          LOGTO_REDIRECT: ${{ secrets.LOGTO_REDIRECT }} # Note: This might be public, consider if it needs to be a secret
          LOGTO_LOGOUT_URI: ${{ secrets.LOGTO_LOGOUT_URI }} # Note: This might be public, consider if it needs to be a secret
        run: |
          pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
